export const SET_SEARCH = 'SET_SEARCH'
export const SET_CURRENT = 'SET_CURRENT'
export const SET_IS_PLAYING = 'SET_IS_PLAYING'
export const ADD_FAVORITES = 'ADD_FAVORITES'
export const SET_VIEWING_HISTORY = 'SET_VIEWING_HISTORY'
export const SET_MOVIES = "SET_MOVIES"